name: Deploy Frontend to Alibaba OSS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup OSSUTIL
        uses: yizhoumo/setup-ossutil@v2
        with:
          ossutil-version: '1.7.18'
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Sync frontend to OSS
        run: |
          ossutil cp -r frontend/ oss://$${{ secrets.OSS_BUCKET_NAME }}/ --update
