name: Deploy Frontend to Alibaba OSS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем ossutil
      - name: Install ossutil
        run: |
          curl -L -o ossutil.zip https://gosspublic.alicdn.com/ossutil/v2/2.1.2/ossutil-2.1.2-linux-amd64.zip
          unzip ossutil.zip
          chmod +x ossutil-2.1.2-linux-amd64/ossutil
          sudo mv ossutil-2.1.2-linux-amd64/ossutil /usr/local/bin/ossutil

      # 3. Загружаем frontend в OSS
      - name: Sync frontend to OSS
        env:
          BUCKET: ${{ secrets.ALIYUN_OSS_BUCKET }}
          ACCESS_KEY: ${{ secrets.ALIYUN_OSS_KEY_ID }}
          SECRET_KEY: ${{ secrets.ALIYUN_OSS_KEY_SECRET }}
          REGION: ${{ secrets.ALIYUN_OSS_REGION }}
        run: |
          ossutil cp -r frontend oss://$BUCKET/ \
            --update \
            --access-key-id $ACCESS_KEY \
            --access-key-secret $SECRET_KEY \
            --region $REGION

      # 4. Отладка
      - name: Show OSS upload report
        run: cat ossutil_output/ossutil_report_*.report || true

